# Generated by Django 5.2.1 on 2025-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
