# Generated by Django 5.2 on 2025-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_reviewer_deleted_at_reviewer_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='best_score',
            field=models.IntegerField(blank=True, help_text='Best quiz score (percentage)', null=True),
        ),
    ]
