# Generated by Django 5.2 on 2025-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_reviewer_best_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='best_score_correct',
            field=models.IntegerField(blank=True, help_text='Number of correct answers in best attempt', null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='best_score_total',
            field=models.IntegerField(blank=True, help_text='Total number of questions', null=True),
        ),
    ]
