# Generated by Django 5.2.3 on 2025-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_productivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='was_completed_on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
