# Generated by Django 5.2 on 2025-08-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity_notes',
            field=models.TextField(blank=True, help_text='Notes about what work was done on this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='has_activity',
            field=models.BooleanField(default=False, help_text='Whether the user has done any work on this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='When the user last worked on this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent_minutes',
            field=models.IntegerField(default=0, help_text='Time spent working on this task in minutes'),
        ),
    ]
