# Generated by Django 5.2 on 2025-08-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_activity_notes_task_has_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evidence_uploaded',
            field=models.BooleanField(default=False, help_text='Whether evidence has been uploaded'),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_description',
            field=models.TextField(blank=True, help_text='Description of the evidence provided'),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Evidence file (screenshot, document, etc.)', null=True, upload_to='task_evidence/'),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When evidence was uploaded', null=True),
        ),
    ]
