# Generated by Django 5.2.3 on 2025-07-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityScaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('completion_rate', models.FloatField(default=0.0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Highly Productive', 'Highly Productive'), ('Productive', 'Productive'), ('Needs Improvement', 'Needs Improvement'), ('Low Productivity', 'Low Productivity'), ('No Tasks', 'No Tasks')], default='No Tasks', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productivity Scale History',
                'verbose_name_plural': 'Productivity Scale History',
                'ordering': ['-period_start', '-created_at'],
                'unique_together': {('user', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
