# Generated by Django 5.2.3 on 2025-08-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productivityscalehistory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productivityscalehistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productivityscalehistory',
            name='period_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productivityscalehistory',
            name='status',
            field=models.CharField(default='No Tasks', max_length=32),
        ),
        migrations.AlterField(
            model_name='productivityscalehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
