# Generated by Django 5.2.1 on 2025-06-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
