# Generated by Django 5.2.3 on 2025-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent for immediate attention'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('lecture', 'Lecture Notes'), ('reading', 'Reading Notes'), ('assignment', 'Assignment Notes'), ('exam', 'Exam Notes'), ('meeting', 'Meeting Notes'), ('personal', 'Personal Notes'), ('work', 'Work Notes'), ('project', 'Project Notes'), ('research', 'Research Notes'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for easy categorization', max_length=500),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(blank=True, help_text="Brief description of the notebook's purpose"),
        ),
        migrations.AddField(
            model_name='notebook',
            name='notebook_type',
            field=models.CharField(choices=[('study', 'Study Notes'), ('meeting', 'Meeting Notes'), ('personal', 'Personal Notes'), ('work', 'Work Notes'), ('project', 'Project Notes'), ('research', 'Research Notes'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='notebook',
            name='urgency_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
    ]
