# Generated by Django 5.2 on 2025-10-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_is_urgent_note_note_type_note_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
