# Generated by Django 5.2 on 2025-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notebook_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
