# Generated by Django 5.2.3 on 2025-11-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notebook_deleted_at_notebook_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='notebook_type',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='urgency_level',
        ),
    ]
