# Generated by Django 5.2.3 on 2025-11-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_fix_notebook_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together=set(),
        ),
    ]
