# Generated by Django 5.2.3 on 2025-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the Terms and Conditions shown to users.', verbose_name='Terms and Conditions Content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
