# Generated by Django 5.2.3 on 2025-08-19 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('reviewer_prompt', 'Reviewer Generation Prompt'), ('quiz_prompt', 'Quiz Generation Prompt'), ('summary_prompt', 'Content Summary Prompt'), ('chat_prompt', 'AI Chat Prompt')], help_text='The type of AI configuration', max_length=50, unique=True, verbose_name='Configuration Type')),
                ('title', models.CharField(help_text='A descriptive title for this configuration', max_length=200, verbose_name='Configuration Title')),
                ('prompt_template', models.TextField(help_text='The prompt template with placeholders like {content}, {text}, etc.', verbose_name='Prompt Template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active', verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this configuration does', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['config_type'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_due', 'Task Due'), ('task_completed', 'Task Completed'), ('note_reminder', 'Note Reminder'), ('study_reminder', 'Study Reminder'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='System Notification', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
