# Generated by Django 5.2.3 on 2025-09-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconfiguration_remove_notification_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='config_type',
            field=models.CharField(choices=[('reviewer_prompt', 'Reviewer Generation Prompt'), ('quiz_prompt', 'Quiz Generation Prompt'), ('summary_prompt', 'Content Summary Prompt'), ('chat_prompt', 'AI Chat Prompt'), ('flashcard_prompt', 'Flashcard Generation Prompt'), ('flashcard_qa_prompt', 'Q&A Pattern Flashcard Prompt'), ('flashcard_heading_prompt', 'Heading Pattern Flashcard Prompt'), ('smart_chunking_prompt', 'Smart Chunking Analysis Prompt')], help_text='The type of AI configuration', max_length=50, unique=True, verbose_name='Configuration Type'),
        ),
    ]
